import {useState} from "react"; import type {FormEvent} from "react"; import {ArrowDownRight,ArrowUpRight,Instagram,Menu,Play,X,Youtube} from "lucide-react";

const images={hero:"https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=2200&q=85",stage:"https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1800&q=85",texture:"https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1400&q=85"};
const nav=["About","Sound","Journey","Connect"];

function App(){
 const [menu,setMenu]=useState(false); const [submitted,setSubmitted]=useState(false);
 const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenu(false)};
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSubmitted(true)};
 return <main className="noise overflow-hidden bg-[#080808] text-[#f5f1e8]">
  <header className="fixed left-0 right-0 top-0 z-40 border-b border-white/10 bg-black/55 backdrop-blur-xl"><div className="mx-auto flex max-w-[1400px] items-center justify-between px-5 py-5 md:px-8">
   <button onClick={()=>go("top")} className="text-xl font-extrabold tracking-[-.05em]">KAYSLEEM<span className="text-[#e8c76a]">.</span></button>
   <nav className="hidden items-center gap-8 text-[11px] font-bold uppercase tracking-[.22em] md:flex">{nav.map(i=><button key={i} onClick={()=>go(i.toLowerCase())} className="text-white/65 transition hover:text-white">{i}</button>)}</nav>
   <button onClick={()=>go("contact")} className="hidden border border-[#e8c76a]/70 px-5 py-3 text-[10px] font-bold uppercase tracking-[.2em] text-[#e8c76a] transition hover:bg-[#e8c76a] hover:text-black md:block">Bookings</button>
   <button aria-label="Menu" onClick={()=>setMenu(!menu)} className="md:hidden">{menu?<X/>:<Menu/>}</button>
  </div>{menu&&<div className="border-t border-white/10 bg-black px-5 py-6 md:hidden">{nav.map(i=><button key={i} onClick={()=>go(i.toLowerCase())} className="block w-full border-b border-white/10 py-4 text-left text-sm uppercase tracking-[.18em]">{i}</button>)}<button onClick={()=>go("contact")} className="mt-5 text-[#e8c76a]">Bookings →</button></div>}</header>

  <section id="top" className="relative flex min-h-screen items-end overflow-hidden px-5 pb-10 pt-28 md:px-10 md:pb-16"><img src={images.hero} alt="Concert atmosphere placeholder" className="absolute inset-0 h-full w-full object-cover opacity-55"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/35 to-black/25"/><div className="relative mx-auto w-full max-w-[1400px]"><p className="mb-5 text-[10px] font-bold uppercase tracking-[.35em] text-[#e8c76a]">Musician · Artist · Sound in motion</p><h1 className="max-w-6xl text-[18vw] font-extrabold leading-[.72] tracking-[-.08em] md:text-[15vw]">KAYSLEEM</h1><div className="mt-8 flex flex-col justify-between gap-8 border-t border-white/20 pt-6 md:flex-row md:items-end"><p className="max-w-md text-sm leading-7 text-white/65 md:text-base">A digital home for the sound, story and world of Kaysleem. Artist details, music, releases and contact information can be added here.</p><button onClick={()=>go("about")} className="flex items-center gap-3 text-xs font-bold uppercase tracking-[.2em]">Explore the artist <ArrowDownRight size={17} className="text-[#e8c76a]"/></button></div></div></section>

  <div className="overflow-hidden border-y border-white/10 py-4"><div className="marquee flex w-max gap-10 whitespace-nowrap text-[10px] font-bold uppercase tracking-[.35em] text-white/35"><span>THE SOUND</span><span>•</span><span>THE STORY</span><span>•</span><span>THE JOURNEY</span><span>•</span><span>THE SOUND</span><span>•</span><span>THE STORY</span><span>•</span><span>THE JOURNEY</span><span>•</span></div></div>

  <section id="about" className="mx-auto grid max-w-[1400px] gap-12 px-5 py-24 md:grid-cols-[.8fr_1.2fr] md:px-10 md:py-36"><div><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#e8c76a]">01 / Meet Kaysleem</p></div><div><h2 className="display text-5xl leading-[.95] md:text-8xl">The person behind <em>the sound.</em></h2><p className="mt-9 max-w-2xl text-base leading-8 text-white/60">[A PERSONAL INTRODUCTION FROM KAYSLEEM WILL GO HERE. This section is intentionally a pitch-ready placeholder until the artist provides his biography, story, influences and artistic identity.]</p><div className="mt-10 grid gap-8 border-t border-white/10 pt-8 sm:grid-cols-2"><div><p className="text-[10px] uppercase tracking-[.25em] text-white/35">Genre</p><p className="mt-2 text-xl">[TO BE ADDED]</p></div><div><p className="text-[10px] uppercase tracking-[.25em] text-white/35">Based in</p><p className="mt-2 text-xl">[TO BE ADDED]</p></div></div></div></section>

  <section id="sound" className="bg-[#e9e3d6] px-5 py-24 text-[#0a0a0a] md:px-10 md:py-32"><div className="mx-auto max-w-[1400px]"><div className="flex flex-col justify-between gap-5 border-b border-black/15 pb-8 md:flex-row md:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.3em] text-black/45">02 / The Sound</p><h2 className="display mt-4 text-6xl md:text-9xl">Listen.</h2></div><p className="max-w-sm text-sm leading-7 text-black/55">A dedicated space for Kaysleem's releases, projects and the songs that define his sound.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[1,2,3].map(n=><article key={n} className="group relative aspect-square overflow-hidden bg-black"><img src={images.texture} alt="" className="h-full w-full object-cover opacity-55 transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/90 to-transparent"/><div className="absolute bottom-0 left-0 right-0 p-6 text-white"><p className="text-[9px] uppercase tracking-[.25em] text-[#e8c76a]">Release {String(n).padStart(2,"0")}</p><h3 className="mt-2 text-2xl font-bold">[SONG / PROJECT TITLE]</h3><p className="mt-1 text-xs text-white/55">[YEAR] · [GENRE]</p><button className="mt-6 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em]">Play preview <Play size={13} fill="currentColor"/></button></div></article>)}</div></div></section>

  <section id="journey" className="mx-auto max-w-[1400px] px-5 py-24 md:px-10 md:py-36"><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#e8c76a]">03 / The Journey</p><h2 className="display mt-5 text-6xl leading-none md:text-8xl">Still<br/><em>becoming.</em></h2></div><div className="border-t border-white/15">{[["2026","[MILESTONE / RELEASE / PERFORMANCE]"],["2025","[MILESTONE / COLLABORATION / PERFORMANCE]"],["20XX","[THE BEGINNING OF THE STORY]"]].map(([y,t])=><div key={y} className="grid grid-cols-[80px_1fr] gap-5 border-b border-white/10 py-7"><span className="text-sm text-[#e8c76a]">{y}</span><span className="text-lg text-white/75 md:text-2xl">{t}</span></div>)}</div></div></section>

  <section className="relative min-h-[70vh] overflow-hidden"><img src={images.stage} alt="Concert lights placeholder" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-black/55"/><div className="relative flex min-h-[70vh] items-center justify-center px-5 text-center"><div><p className="text-[10px] font-bold uppercase tracking-[.4em] text-[#e8c76a]">The visual world</p><h2 className="display mt-5 text-6xl md:text-[9rem]">Feel the<br/><em>moment.</em></h2><p className="mx-auto mt-7 max-w-xl text-sm leading-7 text-white/60">[OFFICIAL ARTIST PHOTOGRAPHY / MUSIC VIDEO / PERFORMANCE VISUALS WILL GO HERE]</p></div></div></section>

  <section id="connect" className="mx-auto max-w-[1400px] px-5 py-24 md:px-10 md:py-32"><div className="grid gap-12 md:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#e8c76a]">04 / Connect</p><h2 className="display mt-5 text-6xl md:text-8xl">Follow the<br/><em>journey.</em></h2></div><div className="grid grid-cols-2 border-l border-white/10">{[["Instagram",Instagram],["YouTube",Youtube],["TikTok",ArrowUpRight],["X / Twitter",ArrowUpRight]].map(([name,Icon])=>{const I=Icon as typeof ArrowUpRight;return <a href="#" onClick={e=>e.preventDefault()} key={name as string} className="group border-b border-r border-white/10 p-6 transition hover:bg-white/[.04]"><I size={19} className="text-[#e8c76a]"/><div className="mt-10 text-lg font-bold">{name as string}</div><div className="mt-2 text-[9px] uppercase tracking-[.15em] text-white/35">[LINK TO BE ADDED]</div></a>})}</div></div></section>

  <section id="contact" className="bg-[#e8c76a] px-5 py-24 text-black md:px-10 md:py-32"><div className="mx-auto grid max-w-[1400px] gap-14 md:grid-cols-[1fr_.75fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.3em] opacity-55">05 / Bookings & Contact</p><h2 className="display mt-5 text-7xl leading-[.8] md:text-[9rem]">Let's create<br/><em>something.</em></h2></div><div><p className="max-w-md text-sm leading-7 opacity-65">For bookings, collaborations, interviews and professional enquiries, use the contact details below once they are supplied.</p><div className="mt-10 space-y-5 border-t border-black/20 pt-6 text-sm"><p><span className="block text-[9px] uppercase tracking-[.2em] opacity-45">Bookings</span><strong>[EMAIL TO BE ADDED]</strong></p><p><span className="block text-[9px] uppercase tracking-[.2em] opacity-45">Phone</span><strong>[PHONE NUMBER TO BE ADDED]</strong></p><p><span className="block text-[9px] uppercase tracking-[.2em] opacity-45">Management</span><strong>[MANAGEMENT CONTACT TO BE ADDED]</strong></p></div><form onSubmit={submit} className="mt-10 space-y-3"><input required placeholder="Your name" className="w-full border-b border-black/30 bg-transparent px-0 py-4 outline-none placeholder:text-black/45"/><input required type="email" placeholder="Your email" className="w-full border-b border-black/30 bg-transparent px-0 py-4 outline-none placeholder:text-black/45"/><textarea required placeholder="Tell us about the enquiry" rows={3} className="w-full resize-none border-b border-black/30 bg-transparent px-0 py-4 outline-none placeholder:text-black/45"/><button className="mt-4 flex items-center gap-3 border border-black px-6 py-4 text-[10px] font-bold uppercase tracking-[.2em] transition hover:bg-black hover:text-[#e8c76a]">Send enquiry <ArrowUpRight size={16}/></button>{submitted&&<p className="text-xs font-semibold">Thanks. This demo form is ready to connect to a real email/backend service.</p>}</form></div></div></section>

  <footer className="border-t border-white/10 px-5 py-8 md:px-10"><div className="mx-auto flex max-w-[1400px] flex-col justify-between gap-5 text-[9px] uppercase tracking-[.22em] text-white/35 md:flex-row"><span>© 2026 KAYSLEEM. Artist website concept.</span><span>Built as a premium pitch prototype.</span><span><p> Powered By <a href="https://philedev.vercel.app" target="_blank">Philedev</a></p></span></div></footer>
 </main>
}
export default App;
